"""CLI surface for run-context and furnished evidence.

Every test here drives the **real** entry point (`uofa_cli.cli.main` via argv, or
`report.run` on a real Namespace). None reconstructs the analysis payload: a
harness that builds its own version of the production call path tests the
harness, and the report goldens were briefly generated by exactly such a harness
with an argument missing (AGENTS.md §13).
"""

from __future__ import annotations

import json
import subprocess
import sys
import types
from pathlib import Path

import pytest

from uofa_cli import card_bundle
from uofa_cli.furnishers import attach, raidex

REPO = Path(__file__).resolve().parents[1]
_CARD = REPO / "packs" / "mrm-nist" / "examples" / "olmo2-13b-instruct" / "card.md"
_RECORD = REPO / "tests" / "fixtures" / "raidex" / "openai__gpt-5.6.json"


@pytest.fixture
def bundle_path(tmp_path: Path) -> Path:
    bundle, _p, _s = card_bundle.card_to_bundle(
        _CARD.read_text(), "mrm-nist", model_id="allenai/OLMo-2-13B-Instruct",
        allow_llm=False)
    bundle["_sufficiencyAssessed"] = True
    path = tmp_path / "bundle.jsonld"
    path.write_text(json.dumps(bundle))
    return path


def _cli(*argv: str) -> subprocess.CompletedProcess:
    """The real CLI, as a user runs it."""
    return subprocess.run([sys.executable, "-m", "uofa_cli.cli", *argv],
                          cwd=REPO, capture_output=True, text=True)


def _report_json(bundle_path: Path, *extra: str) -> dict:
    proc = _cli("report", str(bundle_path), "--pack", "mrm-nist", "--format", "json", *extra)
    assert proc.returncode == 0, proc.stderr or proc.stdout
    return json.loads(proc.stdout)


# ── mutual exclusion (A13.7.4) ──────────────────────────────────────────────

@pytest.mark.parametrize("flags", [
    ["--raidex", str(_RECORD), "--raidex-hub"],
    ["--raidex", str(_RECORD), "--raidex-run"],
    ["--raidex-hub", "--raidex-run"],
])
def test_evidence_sources_are_mutually_exclusive(bundle_path, flags):
    """Silently preferring one source would make the provenance line a guess."""
    proc = _cli("report", str(bundle_path), "--pack", "mrm-nist", *flags)
    assert proc.returncode != 0
    assert "mutually exclusive" in (proc.stdout + proc.stderr)


# ── stated N/As, not silence ────────────────────────────────────────────────

def test_no_evidence_states_not_applicable(bundle_path):
    state = _report_json(bundle_path)
    assert state["eval_sufficiency"] == "not-applicable"
    assert state["has_eval_layer"] is True, "the pack has the layer; this model has no evidence"
    assert not state["mrl_supplied"] and not state["cou_supplied"]


def test_mrl_absent_is_reported_not_assumed(bundle_path):
    """No --mrl means COMPOUND-EV-01 cannot fire, and the readout must say so."""
    proc = _cli("report", str(bundle_path), "--pack", "mrm-nist",
                "--raidex", str(_RECORD))
    assert proc.returncode == 0
    assert "MRL not supplied" in proc.stdout
    assert "COMPOUND-EV-01" not in proc.stdout


# ── run context changes severity, never invents findings ────────────────────

def test_cou_escalates_severity_without_creating_the_finding(bundle_path):
    without = _report_json(bundle_path, "--raidex", str(_RECORD))
    cou = [c for c in without["concerns"] if c["pattern_id"] == "W-EV-COU-05"]
    assert cou and cou[0]["severity"] == "High"

    # a second copy, so the persisted bundle from the first run is not reused
    with_cou = _report_json(bundle_path, "--cou", "screening triage")
    cou2 = [c for c in with_cou["concerns"] if c["pattern_id"] == "W-EV-COU-05"]
    assert cou2 and cou2[0]["severity"] == "Critical"
    assert with_cou["cou_supplied"] is True


def test_mrl_enables_the_compound_rule(bundle_path):
    state = _report_json(bundle_path, "--raidex", str(_RECORD), "--mrl", "3")
    assert state["mrl_supplied"] is True
    assert any(c["pattern_id"] == "COMPOUND-EV-01" for c in state["concerns"])


# ── provenance and persistence ──────────────────────────────────────────────

def test_run_context_and_evidence_are_stamped_and_persisted(bundle_path):
    _report_json(bundle_path, "--raidex", str(_RECORD), "--cou", "triage", "--mrl", "3")
    saved = json.loads(bundle_path.read_text())
    prov = set(saved["fieldProvenance"])
    assert "decisionContextOfUse=run-context" in prov
    assert "decisionRiskLevel=run-context" in prov
    assert "hasValidationResult=extracted" in prov, "a published record is not a live run"
    assert saved["furnisherOutputHash"].startswith("sha256:")

    # Re-derivable: the saved bundle reproduces the readout with no flags.
    again = _report_json(bundle_path)
    assert again["cou_supplied"] and again["mrl_supplied"]
    assert again["eval_sufficiency"] == "assessed"


def test_operator_context_is_distinct_from_the_models_own(bundle_path):
    """--mrl must not be confused with the pack's assumed MRL-3 posture."""
    saved_before = json.loads(bundle_path.read_text())
    assert saved_before["modelRiskLevel"] == 3, "pack posture is present from the start"
    assert "decisionRiskLevel" not in saved_before, "but the operator has stated nothing"

    state = _report_json(bundle_path)
    assert state["mrl_supplied"] is False, (
        "the pack's assumed MRL must not read as an operator-stated risk level")


# ── the live-run seam (stubbed; see docs/live-run-verification.md) ───────────

def _stub_runner(record_path: Path):
    def run(cmd):
        out = Path(cmd[cmd.index("--out") + 1])
        out.write_text(record_path.read_text())
        return types.SimpleNamespace(returncode=0, stdout="", stderr="")
    return run


def test_live_run_is_stamped_furnished_run_not_extracted(tmp_path):
    """A live run and a published lookup are different claims about the evidence."""
    bundle = {"id": "https://example.org/m"}
    res = attach.run_raidex(bundle, "local/checkpoint",
                            runner=_stub_runner(_RECORD), workdir=tmp_path)
    assert res.ok and res.live_run
    prov = set(bundle["fieldProvenance"])
    assert "hasValidationResult=furnished-run" in prov
    assert "hasValidationResult=extracted" not in prov


def test_live_run_gets_no_severity_discount(tmp_path):
    """Freshness is not sufficiency: the same record yields the same evidence."""
    live = {"id": "https://example.org/m"}
    attach.run_raidex(live, "m", runner=_stub_runner(_RECORD), workdir=tmp_path)
    published = {"id": "https://example.org/m"}
    attach.attach_raidex(published, local_path=_RECORD)
    assert live["hasValidationResult"] == published["hasValidationResult"]


def test_subprocess_failure_surfaces_raidex_stderr(tmp_path):
    fail = lambda cmd: types.SimpleNamespace(  # noqa: E731
        returncode=2, stdout="", stderr="CUDA out of memory")
    res = attach.run_raidex({"id": "x"}, "m", runner=fail, workdir=tmp_path)
    assert not res.ok and "CUDA out of memory" in res.detail


def test_missing_raidex_is_a_reportable_state_not_a_crash(tmp_path, monkeypatch):
    monkeypatch.setattr(attach, "raidex_installed", lambda: (False, ""))
    res = attach.run_raidex({"id": "x"}, "m", workdir=tmp_path)
    assert not res.ok
    assert "pip install uofa[raidex]" in res.detail
    assert "--raidex-hub" in res.detail, "the other sources still work; say so"


def test_preflight_states_no_cost_number_it_cannot_support():
    """A preflight that under-states spend is worse than none."""
    text = attach.preflight_statement("owner/model")
    assert "NOT ESTIMATED" in text
    assert attach.RAIDEX_UNVERIFIED
    for constituent in ("bbq", "simpleqa", "wmdp"):
        assert constituent in text


# ── a published lookup that finds nothing is a stated absence ───────────────

def test_model_absent_from_the_dataset_is_not_an_error(tmp_path):
    bundle = {"id": "https://example.org/m"}
    res = attach.attach_raidex(bundle, model_id="nobody/not-a-real-model", use_hub=True)
    assert not res.ok
    assert "hasValidationResult" not in bundle, "no evidence means no nodes, not empty ones"
