"""CLI surface for run-context and furnished evidence.

Every test here drives the **real** entry point (`uofa_cli.cli.main` via argv, or
`report.run` on a real Namespace). None reconstructs the analysis payload: a
harness that builds its own version of the production call path tests the
harness, and the report goldens were briefly generated by exactly such a harness
with an argument missing (AGENTS.md §13).
"""

from __future__ import annotations

import json
import subprocess
import sys
import types
from pathlib import Path

import pytest

from uofa_cli import card_bundle
from uofa_cli.furnishers import attach, raidex

REPO = Path(__file__).resolve().parents[1]
_CARD = REPO / "packs" / "model-credibility" / "examples" / "olmo2-13b-instruct" / "card.md"
_RECORD = REPO / "tests" / "fixtures" / "raidex" / "openai__gpt-5.6.json"


@pytest.fixture
def bundle_path(tmp_path: Path) -> Path:
    bundle, _p, _s = card_bundle.card_to_bundle(
        _CARD.read_text(), "model-credibility", model_id="allenai/OLMo-2-13B-Instruct",
        allow_llm=False)
    bundle["_sufficiencyAssessed"] = True
    path = tmp_path / "bundle.jsonld"
    path.write_text(json.dumps(bundle))
    return path


def _cli(*argv: str) -> subprocess.CompletedProcess:
    """The real CLI, as a user runs it."""
    return subprocess.run([sys.executable, "-m", "uofa_cli.cli", *argv],
                          cwd=REPO, capture_output=True, text=True)


def _report_json(bundle_path: Path, *extra: str) -> dict:
    proc = _cli("report", str(bundle_path), "--pack", "model-credibility", "--format", "json", *extra)
    assert proc.returncode == 0, proc.stderr or proc.stdout
    return json.loads(proc.stdout)


# ── mutual exclusion (A13.7.4) ──────────────────────────────────────────────

@pytest.mark.parametrize("flags", [
    ["--raidex", str(_RECORD), "--raidex-hub"],
    ["--raidex", str(_RECORD), "--raidex-run"],
    ["--raidex-hub", "--raidex-run"],
])
def test_evidence_sources_are_mutually_exclusive(bundle_path, flags):
    """Silently preferring one source would make the provenance line a guess."""
    proc = _cli("report", str(bundle_path), "--pack", "model-credibility", *flags)
    assert proc.returncode != 0
    assert "mutually exclusive" in (proc.stdout + proc.stderr)


# ── stated N/As, not silence ────────────────────────────────────────────────

def test_no_evidence_states_not_applicable(bundle_path):
    state = _report_json(bundle_path)
    assert state["eval_sufficiency"] == "not-applicable"
    assert state["has_eval_layer"] is True, "the pack has the layer; this model has no evidence"
    assert not state["mrl_supplied"] and not state["cou_supplied"]


def test_mrl_absent_is_reported_not_assumed(bundle_path):
    """No --mrl means COMPOUND-EV-01 cannot fire, and the readout must say so."""
    proc = _cli("report", str(bundle_path), "--pack", "model-credibility",
                "--raidex", str(_RECORD))
    assert proc.returncode == 0
    assert "MRL not supplied" in proc.stdout
    assert "COMPOUND-EV-01" not in proc.stdout


# ── run context changes severity, never invents findings ────────────────────

def test_cou_escalates_severity_without_creating_the_finding(bundle_path):
    without = _report_json(bundle_path, "--raidex", str(_RECORD))
    cou = [c for c in without["concerns"] if c["pattern_id"] == "W-EV-COU-05"]
    assert cou and cou[0]["severity"] == "High"

    # a second copy, so the persisted bundle from the first run is not reused
    with_cou = _report_json(bundle_path, "--cou", "screening triage")
    cou2 = [c for c in with_cou["concerns"] if c["pattern_id"] == "W-EV-COU-05"]
    assert cou2 and cou2[0]["severity"] == "Critical"
    assert with_cou["cou_supplied"] is True


def test_mrl_enables_the_compound_rule(bundle_path):
    state = _report_json(bundle_path, "--raidex", str(_RECORD), "--mrl", "3")
    assert state["mrl_supplied"] is True
    assert any(c["pattern_id"] == "COMPOUND-EV-01" for c in state["concerns"])


# ── provenance and persistence ──────────────────────────────────────────────

def test_run_context_and_evidence_are_stamped_and_persisted(bundle_path):
    _report_json(bundle_path, "--raidex", str(_RECORD), "--cou", "triage", "--mrl", "3")
    saved = json.loads(bundle_path.read_text())
    prov = set(saved["fieldProvenance"])
    assert "decisionContextOfUse=run-context" in prov
    assert "decisionRiskLevel=run-context" in prov
    assert "hasValidationResult=extracted" in prov, "a published record is not a live run"
    assert saved["furnisherOutputHash"].startswith("sha256:")

    # Re-derivable: the saved bundle reproduces the readout with no flags.
    again = _report_json(bundle_path)
    assert again["cou_supplied"] and again["mrl_supplied"]
    assert again["eval_sufficiency"] == "assessed"


def test_operator_context_is_distinct_from_the_models_own(bundle_path):
    """--mrl must not be confused with the pack's assumed MRL-3 posture."""
    saved_before = json.loads(bundle_path.read_text())
    assert saved_before["modelRiskLevel"] == 3, "pack posture is present from the start"
    assert "decisionRiskLevel" not in saved_before, "but the operator has stated nothing"

    state = _report_json(bundle_path)
    assert state["mrl_supplied"] is False, (
        "the pack's assumed MRL must not read as an operator-stated risk level")


# ── the live-run seam (stubbed; see docs/live-run-verification.md) ───────────

def _stub_runner(record_path: Path):
    def run(cmd):
        out = Path(cmd[cmd.index("--output") + 1])
        out.write_text(record_path.read_text())
        return types.SimpleNamespace(returncode=0, stdout="", stderr="")
    return run


def test_live_run_is_stamped_furnished_run_not_extracted(tmp_path):
    """A live run and a published lookup are different claims about the evidence."""
    bundle = {"id": "https://example.org/m"}
    res = attach.run_raidex(bundle, "local/checkpoint",
                            runner=_stub_runner(_RECORD), workdir=tmp_path)
    assert res.ok and res.live_run
    prov = set(bundle["fieldProvenance"])
    assert "hasValidationResult=furnished-run" in prov
    assert "hasValidationResult=extracted" not in prov


def test_live_run_gets_no_severity_discount(tmp_path):
    """Freshness is not sufficiency: the same record yields the same evidence."""
    live = {"id": "https://example.org/m"}
    attach.run_raidex(live, "m", runner=_stub_runner(_RECORD), workdir=tmp_path)
    published = {"id": "https://example.org/m"}
    attach.attach_raidex(published, local_path=_RECORD)
    assert live["hasValidationResult"] == published["hasValidationResult"]


def test_subprocess_failure_surfaces_raidex_stderr(tmp_path):
    fail = lambda cmd: types.SimpleNamespace(  # noqa: E731
        returncode=2, stdout="", stderr="CUDA out of memory")
    res = attach.run_raidex({"id": "x"}, "m", runner=fail, workdir=tmp_path)
    assert not res.ok and "CUDA out of memory" in res.detail


def test_missing_raidex_is_a_reportable_state_not_a_crash(tmp_path, monkeypatch):
    monkeypatch.setattr(attach, "raidex_installed", lambda: (False, ""))
    res = attach.run_raidex({"id": "x"}, "m", workdir=tmp_path)
    assert not res.ok
    assert "pip install uofa[raidex]" in res.detail
    assert "--raidex-hub" in res.detail, "the other sources still work; say so"


def test_preflight_never_substitutes_a_guess_for_a_missing_estimate():
    """Superseded: UofA no longer estimates, it relays raidex's --dry-run.

    The earlier version asserted the preflight prints "NOT ESTIMATED", which was
    right while UofA had no basis for a number. raidex ships --dry-run with real
    per-constituent pricing, so asking the furnisher replaced refusing to answer.
    What must NOT change is the failure mode: an unavailable estimate says so.
    """
    unreachable = lambda cmd: types.SimpleNamespace(  # noqa: E731
        returncode=1, stdout="", stderr="")
    text = attach.preflight_statement("owner/model", runner=unreachable)
    assert "UNKNOWN" in text
    assert "$" not in text, "no invented figure when the furnisher did not supply one"


# ── a published lookup that finds nothing is a stated absence ───────────────

def test_model_absent_from_the_dataset_is_not_an_error(tmp_path):
    bundle = {"id": "https://example.org/m"}
    res = attach.attach_raidex(bundle, model_id="nobody/not-a-real-model", use_hub=True)
    assert not res.ok
    assert "hasValidationResult" not in bundle, "no evidence means no nodes, not empty ones"


# ── the contract a stub cannot falsify ──────────────────────────────────────

def test_subprocess_uses_raidex_actual_flag_names(tmp_path):
    """--model is a required NAMED flag and the output flag is --output.

    The original implementation used a positional model and `--out`, and every
    stubbed test passed: a stub that ignores argv cannot falsify argv. This
    inspects the argv actually built, which is the part that was wrong.
    """
    seen = {}

    def capture(cmd):
        seen["cmd"] = cmd
        Path(cmd[cmd.index("--output") + 1]).write_text(_RECORD.read_text())
        return types.SimpleNamespace(returncode=0, stdout="", stderr="")

    attach.run_raidex({"id": "x"}, "openai/gpt-4o-mini", runner=capture, workdir=tmp_path)
    cmd = seen["cmd"]
    assert cmd[:2] == ["raidex", "eval"]
    assert "--model" in cmd and cmd[cmd.index("--model") + 1] == "openai/gpt-4o-mini"
    assert "--output" in cmd
    assert "--out" not in cmd, "--out is not a raidex flag; --output is"
    assert "openai/gpt-4o-mini" not in cmd[2:3], "the model is named, not positional"


def test_a_sweep_that_furnishes_nothing_is_not_reported_as_success(tmp_path):
    """A failed sweep must not read as 'no reported evaluation to assess'.

    Found by a real `raidex eval --offline` run: every constituent errored,
    rai_coverage came back "0/9", and reporting success made the readout claim
    there was nothing to assess -- a materially more reassuring statement than
    'the sweep failed'.
    """
    empty = {
        "config": {"model_id": "m/n", "backend_version": "0.1.0"},
        "results": {k: {"value": None, "normalized": None,
                        "error": "lm_eval exited 1: connection refused"}
                    for k in ("bbq", "wmdp", "ethics")},
        "composite": {"rai_score": None, "rai_coverage": "0/9", "rai_coverage_pct": 0},
    }

    def runner(cmd):
        Path(cmd[cmd.index("--output") + 1]).write_text(json.dumps(empty))
        return types.SimpleNamespace(returncode=0, stdout="", stderr="")

    bundle = {"id": "https://example.org/m"}
    res = attach.run_raidex(bundle, "m/n", runner=runner, workdir=tmp_path)
    assert not res.ok, "zero usable results is not success"
    assert "0/9" in res.detail and "furnished no usable results" in res.detail
    assert "hasValidationResult" not in bundle


def test_attempted_but_empty_reads_differently_from_no_evaluation(tmp_path):
    """The two absences are different claims and must not share a sentence."""
    from uofa_cli.commands import report as R

    bundle, _p, _s = card_bundle.card_to_bundle(
        _CARD.read_text(), "model-credibility", model_id="a/b", allow_llm=False)
    bundle["_sufficiencyAssessed"] = True

    assert R._eval_sufficiency(bundle, True) == "not-applicable"
    bundle["_evaluationAttempted"] = True
    assert R._eval_sufficiency(bundle, True) == "attempted-empty"


def test_preflight_relays_raidex_estimate_rather_than_inventing_one():
    """UofA does not estimate cost; it asks the furnisher, which knows."""
    def dry(cmd):
        assert "--dry-run" in cmd
        return types.SimpleNamespace(
            returncode=0, stdout="Cost estimate:\n  bbq  $0.72\n  TOTAL  $2.39\n", stderr="")

    text = attach.preflight_statement("openai/gpt-4o-mini", runner=dry)
    assert "$2.39" in text and "dry-run" in text
    assert "not a quote" in text


def test_preflight_says_unknown_when_the_dry_run_fails():
    fail = lambda cmd: types.SimpleNamespace(returncode=1, stdout="", stderr="")  # noqa: E731
    text = attach.preflight_statement("m", runner=fail)
    assert "UNKNOWN" in text and "unbounded spend" in text
