"""Run SIP + the real `uofa check` over the corpus → the per-case table.

For every evaluation case:
  1. Build a COU scope declaring the surrogate's training envelope (the saved
     train-split bounds) and this case's evaluation point.
  2. `run_interrogation` → a signed SIP bundle (SIP measures residual vs the
     RANS reference + the envelope-containment fact).
  3. Map the verified bundle to surrogate-pack JSON-LD via the v2
     `sip_bundle_reader`, then run `check.run_structured(pack=["surrogate"])`
     and read **whether W-SURR-03 fired** from `result.rules.firings` — the real
     derivation-aware check path, NOT recomputed here.
  4. Record one row: eval point, SIP containment fact, w_surr_03_fired,
     predicted Cl/Cd, RANS reference Cl/Cd, and true error |pred − ref|.

Emits a tidy per-case table (CSV + JSONL). The table is committable; raw
AirfRANS is not. The adapter is generated by reusing `interrogate init`'s
template codegen (no interactive wizard, no LLM).
"""

from __future__ import annotations

import argparse
import csv
import json
import tempfile
from pathlib import Path

from harness.datasets import FEATURES, TARGETS, Case, Corpus

COLUMNS = [
    "case_id", "reynolds", "aoa",
    "eval_point_in_envelope",     # SIP's containment fact
    "w_surr_03_fired",            # read from the real `uofa check`
    "pred_cl", "pred_cd", "ref_cl", "ref_cd", "err_cl", "err_cd",
]


def _generate_adapter(model_path: Path, out_dir: Path) -> str:
    """Reuse `interrogate init`'s template codegen (no LLM) for the adapter."""
    from uofa_cli.interrogate import init_wizard

    src = init_wizard.generate_adapter_source(
        class_name="GeneratedAdapter", model_format="sklearn",
        model_path=str(model_path), input_names=list(FEATURES), output_names=list(TARGETS),
    )
    adapter_path = out_dir / "sip_adapter.py"
    adapter_path.write_text(src, encoding="utf-8")
    return f"{adapter_path}:GeneratedAdapter"


def _scope(envelope: dict, case: Case) -> dict:
    return {
        "subject": {"surrogateId": "airfrans-mlp", "modelVersion": "1.0.0",
                    "surrogateType": "data-driven-emulator", "modelFingerprint": "sha256:harness"},
        "trainingEnvelope": {"dimensions": [
            {"name": "reynolds", "min": envelope["reynolds"][0], "max": envelope["reynolds"][1]},
            {"name": "aoa", "min": envelope["aoa"][0], "max": envelope["aoa"][1]},
        ]},
        "evaluationPoint": {"coordinates": [
            {"name": "reynolds", "value": case.reynolds},
            {"name": "aoa", "value": case.aoa},
        ]},
        "declaredPhysicsConstraint": [],
    }


def _w_surr_03_fired(cou_path: Path) -> tuple[bool, str | None]:
    """Read 'W-SURR-03 fired?' from the real `uofa check` structured output."""
    from uofa_cli.commands.check import run_structured

    args = argparse.Namespace(
        file=cou_path, pubkey=None, context=None, rules=None, skip_rules=False, build=False,
        enable_oos=False, disable_oos=False, no_color=True, verbose=False, repo_root=None,
        pack=["surrogate"],
    )
    result = run_structured(args)
    if result.rules is None:
        return False, getattr(result, "rules_error", "rules did not run")
    pids = {f["patternId"] for f in (result.rules.firings or [])}
    return ("W-SURR-03" in pids), None


def run_corpus(corpus: Corpus, model_path: Path, envelope: dict, out_dir: Path,
               *, limit: int | None = None) -> list[dict]:
    import numpy as np
    import joblib
    from uofa_cli import integrity, paths
    from uofa_cli.interrogate import run_interrogation
    from uofa_cli.readers.sip_bundle_reader import read_sip_bundle

    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    paths.set_active_pack(["surrogate"])

    model = joblib.load(model_path)
    adapter_ref = _generate_adapter(model_path, out_dir)
    key = out_dir / "harness.key"
    if not key.exists():
        integrity.generate_keypair(key)
    pub = key.with_suffix(".pub")

    cases = corpus.evaluation[:limit] if limit else corpus.evaluation
    rows: list[dict] = []
    work = Path(tempfile.mkdtemp(prefix="airfrans_corpus_"))

    for case in cases:
        # SIP measurement bundle for this case (1-point benchmark + RANS reference).
        bench = work / "bench.npz"
        ref = work / "ref.npz"
        np.savez(bench, inputs=np.array([case.features()], dtype=float),
                 input_names=np.array(list(FEATURES)))
        np.savez(ref, **{"ref__cl": np.array([case.cl]), "ref__cd": np.array([case.cd])})
        bundle = work / "bundle.json"
        run_interrogation(
            adapter_ref=adapter_ref, benchmark_path=bench, reference_path=ref,
            scope=_scope(envelope, case), output_path=bundle, key_path=key,
            bundle_id=f"airfrans-{case.case_id}", generated_at="2026-05-30T00:00:00Z",
        )

        # v2 map → surrogate-pack JSON-LD → real `uofa check` → fired flag.
        cou = work / "cou.jsonld"
        doc = read_sip_bundle(bundle, measurement_pubkey=pub)
        cou.write_text(json.dumps(doc), encoding="utf-8")
        fired, _ = _w_surr_03_fired(cou)

        in_env = doc_in_envelope(bundle)
        pred = np.asarray(model.predict([case.features()]))[0]
        pred_cl, pred_cd = float(pred[0]), float(pred[1])
        rows.append({
            "case_id": case.case_id, "reynolds": case.reynolds, "aoa": case.aoa,
            "eval_point_in_envelope": in_env,
            "w_surr_03_fired": fired,
            "pred_cl": pred_cl, "pred_cd": pred_cd,
            "ref_cl": case.cl, "ref_cd": case.cd,
            "err_cl": abs(pred_cl - case.cl), "err_cd": abs(pred_cd - case.cd),
        })

    _write_table(rows, out_dir)
    return rows


def doc_in_envelope(bundle_path: Path) -> bool | None:
    """SIP's evaluation-point-in-envelope containment fact (from the bundle)."""
    bundle = json.loads(Path(bundle_path).read_text(encoding="utf-8"))
    return bundle.get("measurements", {}).get("envelopeCoverage", {}).get("evaluationPointInEnvelope")


def _write_table(rows: list[dict], out_dir: Path) -> tuple[Path, Path]:
    csv_path = out_dir / "per_case.csv"
    jsonl_path = out_dir / "per_case.jsonl"
    with open(csv_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=COLUMNS)
        writer.writeheader()
        writer.writerows(rows)
    with open(jsonl_path, "w") as f:
        for row in rows:
            f.write(json.dumps(row) + "\n")
    return csv_path, jsonl_path
