"""INV-17 — count judgments where a rule fired on an absence the judge says is present.

    python studies/phase2_5a/count_prose_vs_property.py

Emits the candidate set and a fixed-seed sample of 30. The 30 were classified by
hand; the verdicts are inlined below so the precision figure is auditable rather
than asserted. Re-running reproduces the same sample (seed 3).

The filtering that matters is `PRECOND`. Six rules are DEFINED as "X present but Y
absent" -- W-AL-02 is "UQ present but no sensitivity analysis", W-CON-05 is
"activity present but no evidence binding". For those, a judge writing "UQ is
present" restates the rule's precondition rather than contradicting it, so a naive
search scores every correct firing as a disagreement. W-AL-02 alone contributed 205
sentences of pure artifact before this exclusion.
"""

from __future__ import annotations

import collections
import glob
import json
import math
import random
import re
from pathlib import Path

RUN = Path("dev/build/adversarial/phase3/production/run-1")
RULES = Path("packs/core/rules/uofa_weakener.rules")

# Rules whose definition pairs a present X with an absent Y. Excluded wholesale.
PRECOND = {"W-AL-02", "W-CON-05", "W-CON-04", "W-SI-02", "W-AR-02", "W-CON-01"}

# The rule's own absent property, so "it exists" contradicts the firing.
SUBJECT = {
    "W-AR-05": r"comparator|comparison|experimental (?:data|result)|benchmark|reference data|measured data",
    "W-AL-01": r"uncertaint|\bUQ\b|error bar|confidence interval|tolerance",
    "W-ON-01": r"context of use|\bCOU\b|intended use",
    "W-ON-02": r"applicabilit|operating envelope|envelope|bound|range of validity|domain",
    "W-EP-01": r"provenance|evidence chain|traceab|generated by|derived from",
    "W-EP-02": r"provenance|generated by|activity|traceab",
    "W-AR-01": r"acceptance criteri|threshold|requirement|pass.?fail",
    "W-SI-01": r"signature|signed|signing",
    "W-CON-02": r"identifier|resolve|reference",
    "W-PROV-01": r"provenance|chain|attribution",
}
SUBJECT = {k: re.compile(v, re.I) for k, v in SUBJECT.items()}

EXIST = re.compile(r"""(
    \b(?:do|does|are|is|were|was)\s+(?:indeed\s+|in\s+fact\s+)?
        (?:exist|present|provided|documented|described|reported|included|stated|specified)
  | \b(?:in|from)\s+the\s+(?:prose|narrative|text|description|discussion)
  | \bdoes\s+(?:report|include|provide|document|describe|state|specify|contain)
)""", re.X | re.I)
NEG = re.compile(r"\b(?:no|not|never|nor|without|absent|lack(?:s|ing)?|missing|fails? to|neither)\b", re.I)
DISAGREE = re.compile(r"\b(but|however|though|although|yet|rejected|does not fit|doesn't fit"
                      r"|not applicable|unrelated|does not apply|false positive|misfire|mis-?fired"
                      r"|incorrectly|overreach|spurious|not correctly|flaw)\b", re.I)
# Judge agreeing: "X present ... but lacks/absent Y".
AGREE = re.compile(r"(?:present|exists?|provided|documented|described)\b[^.;]{0,120}?"
                   r"\b(?:but|yet|however|while|though)\b[^.;]{0,120}?"
                   r"\b(?:lacks?|absent|missing|no |not |never|fails? to)", re.I)
RID = re.compile(r"\bW-[A-Z]+-\d+\b")

# Hand-classified verdicts for the seed-3 sample of 30, 1-indexed as printed.
# 18/30 genuine. The 12 rejects split two ways, and the second kind is a finding:
#   - judge agrees with the firing ("ValidationResult present but under-described")
#   - judge asserts the rule's PRECONDITION is present, not its absent property --
#     "W-ON-02 is a false positive because a detailed ContextOfUse is provided", when
#     W-ON-02 reads the envelope, and a declared COU is what makes it eligible to
#     fire at all. That is a judge misreading the rule, not a rule defect.
VERIFIED_GENUINE = {1, 2, 5, 6, 8, 9, 10, 12, 13, 14, 15, 16, 20, 22, 24, 28, 29, 30}
SAMPLE_N = 30


def novalue_rules() -> set[str]:
    """The absence-checking set, read from the catalog rather than hard-coded."""
    text = RULES.read_text()
    out = set()
    for block in re.split(r"\n(?=#\s*W-[A-Z]+-\d+:)", text):
        m = re.search(r"#\s*(W-[A-Z]+-\d+):", block)
        if m and "noValue(" in block:
            out.add(m.group(1))
    return out


def wilson(k: int, n: int, z: float = 1.96) -> tuple[float, float]:
    if n == 0:
        return (0.0, 0.0)
    p = k / n
    d = 1 + z * z / n
    centre = p + z * z / (2 * n)
    margin = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n))
    return ((centre - margin) / d, (centre + margin) / d)


def candidates() -> list[dict]:
    eligible = (novalue_rules() & set(SUBJECT)) - PRECOND
    hits = []
    for path in sorted(glob.glob(str(RUN / "judgments_*.jsonl"))):
        judge = Path(path).stem[-1]
        for line in open(path):
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                continue
            steps = rec.get("reasoning_steps") or {}
            fired = set(RID.findall(steps.get("rule_firings_inspected") or ""))
            if not fired:
                continue
            fields = {
                "reasoning": rec.get("reasoning"),
                "alternative_rule_analysis": rec.get("alternative_rule_analysis"),
                "steps.instantiation_check": steps.get("instantiation_check"),
            }
            for fname, text in fields.items():
                for sent in re.split(r"(?<=[.;])\s+", text or ""):
                    if not DISAGREE.search(sent) or AGREE.search(sent):
                        continue
                    for rid in set(RID.findall(sent)) & fired & eligible:
                        m = EXIST.search(sent)
                        if not m or NEG.search(sent[max(0, m.start() - 45):m.start()]):
                            continue
                        if not SUBJECT[rid].search(sent):
                            continue
                        hits.append({"judge": judge, "case": rec.get("case_id"),
                                     "rule": rid, "verdict": rec.get("verdict"),
                                     "field": fname, "sent": sent.strip()})
    return hits


def main() -> int:
    hits = candidates()
    cases = {h["case"] for h in hits}
    k, n = len(VERIFIED_GENUINE), SAMPLE_N
    lo, hi = wilson(k, n)

    print(f"candidate sentences : {len(hits)}")
    print(f"distinct cases      : {len(cases)}")
    print(f"hand-verified       : {k}/{n} = {k/n:.1%}  Wilson 95% CI [{lo:.1%}, {hi:.1%}]")
    print(f"estimated genuine   : {len(cases)*k/n:.0f}  range [{len(cases)*lo:.0f}, {len(cases)*hi:.0f}]")

    print("\nby rule:")
    per = collections.Counter(h["rule"] for h in hits)
    for rid, cnt in per.most_common():
        ncase = len({h["case"] for h in hits if h["rule"] == rid})
        print(f"  {rid:<11}{cnt:>4} sentences {ncase:>4} cases")
    print("\nby judge (stated reasoning volume, NOT disagreement rate):",
          dict(collections.Counter(h["judge"] for h in hits)))

    random.seed(3)
    print(f"\n--- the {SAMPLE_N} hand-classified ---")
    for i, h in enumerate(random.sample(hits, SAMPLE_N), 1):
        mark = "GENUINE" if i in VERIFIED_GENUINE else "  no   "
        print(f"[{i:02d}] {mark} {h['rule']:<10} {h['sent'][:110]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
