"""D3/D4 undercutting (model version drift) — Phase 2 W-AR-04.

W-AR-04 detects validation results whose generating ModelConfiguration
declares a ``modelVersion`` different from the UofA's
``currentModelVersion`` — evidence was produced by a build that no longer
matches the version of record. Severity: High.
"""

from __future__ import annotations

from uofa_cli.adversarial.prompts.base import (
    BASE_SYSTEM_PROMPT,
    build_user_prompt,
    validate_subtlety_examples,
)

PROMPT_VERSION = "v1.0.0"

SYSTEM_PROMPT = BASE_SYSTEM_PROMPT

WEAKENER_DESCRIPTION = (
    "model version drift — a ValidationResult was generated under a "
    "ModelConfiguration whose modelVersion differs from the UofA's "
    "currentModelVersion, so the supporting evidence no longer applies "
    "to the model of record"
)

TASK = (
    "generate a UnitOfAssurance package that declares a `currentModelVersion` "
    "field but at least one ValidationResult is generated by a "
    "ModelConfiguration whose modelVersion is different (e.g., a prior "
    "build). The narrative should be plausible — the configuration name "
    "should look real (e.g., 'ansys-cfx-15-build-2024-08')."
)

TRIGGER_BLOCK = (
    "Emit `currentModelVersion: \"<some-version>\"` on the top-level "
    "UnitOfAssurance. Then emit at least one ValidationResult inline "
    "object with a `wasGeneratedBy` link to a ModelConfiguration node "
    "whose `modelVersion` differs from the UofA's currentModelVersion. "
    "The mismatch must be on the modelVersion field, not on activity "
    "type or comparator."
)

SUBTLETY_GUIDANCE = {
    "low": (
        "Make the version drift obvious — UofA currentModelVersion is "
        "'2026-q1-build-7' but the ValidationResult's ModelConfiguration "
        "modelVersion is '2024-q3-build-2', a multi-year drift."
    ),
    "medium": (
        "Drift is one minor version (2026-q1-build-7 vs 2026-q1-build-5). "
        "The narrative does not mention the version difference."
    ),
    "high": (
        "Drift is a single patch-level revision (e.g., 2026-q1-build-7 vs "
        "2026-q1-build-7-rc2). The narrative emphasizes that the "
        "ModelConfiguration is 'effectively the same build' without "
        "actually re-running validation under the released version."
    ),
}

validate_subtlety_examples(SUBTLETY_GUIDANCE)


EXTRA_SCHEMA_RULES = (
    "- `currentModelVersion`: top-level string on the UnitOfAssurance.\n"
    "- `wasGeneratedBy` on a ValidationResult: IRI of a ModelConfiguration\n"
    "  inline object that carries `modelVersion: \"...\"`."
)


def render(spec, context: dict) -> tuple[str, str]:
    user = build_user_prompt(
        weakener=spec.target_weakener,
        weakener_description=WEAKENER_DESCRIPTION,
        defeater_type="D4 — undercutting (model version drift)",
        subtlety=spec.subtlety,
        subtlety_guidance=SUBTLETY_GUIDANCE[spec.subtlety],
        base_cou_identity=context.get("identity"),
        context_of_use=context.get("context_of_use"),
        factor_scaffold=context.get("factor_scaffold", []),
        context_url=context.get("context_url", ""),
        decision=spec.decision,
        task=TASK,
        trigger_block=TRIGGER_BLOCK,
        extra_schema_rules=EXTRA_SCHEMA_RULES,
    )
    return SYSTEM_PROMPT, user
