"""Phase 3 reviewer prep packet generation — Phase 2 Spec v1.8 §10.6.

`uofa adversarial prep-review` reads a classified outcomes.csv, filters
COV-MISS / COV-WRONG cases (deduplicated by spec_id), and writes per-case
Markdown packets plus an INDEX.md. The packets are designed for Upwork
expert reviewers in Phase 3 Stage 1 onboarding.

Per-packet structure (per §10.6):
- Source taxonomy attribution (registry citation, sub-type description)
- Spec description (from spec YAML)
- Generated package summary (path, model, subtlety, variant)
- Outcome (classification, rules fired, expected target rule)
- What the existing catalog covers in this neighborhood
  (auto-generated by source_taxonomy lookup)
- Four reviewer questions calibrated for Stage 4 statistics
- Embedded JSON-LD of representative variant

INDEX.md:
- Sorted by §6.7 candidate priority first, then source_taxonomy alpha
"""

from __future__ import annotations

import argparse
import csv
import json
from dataclasses import dataclass
from pathlib import Path

from uofa_cli import paths
from uofa_cli.output import error, info, result_line, warn


#: Outcome classes that route into reviewer packets per §10.6.
_REVIEWABLE_OUTCOMES: frozenset[str] = frozenset({"COV-MISS", "COV-WRONG"})


@dataclass
class _ReviewableCase:
    spec_id: str
    target_weakener: str | None
    source_taxonomy: str | None
    coverage_intent: str
    outcome_class: str
    subtlety: str
    rules_fired: str
    is_section_6_7_candidate: bool


def _normalize_include(arg_value: str | None) -> set[str]:
    """Parse --include into a set of upper-cased outcome class names."""
    default = {"COV-MISS", "COV-WRONG"}
    if not arg_value:
        return default
    out = set()
    for part in arg_value.split(","):
        cls = part.strip().upper()
        if not cls:
            continue
        # Permit short forms ('cov-miss', 'miss', etc.)
        if not cls.startswith("COV-"):
            cls = f"COV-{cls}"
        out.add(cls)
    return out or default


def _load_source_taxonomies() -> dict:
    """Load packs/core/source_taxonomies.json. Returns empty dict if missing."""
    try:
        root = paths.find_repo_root()
    except FileNotFoundError:
        return {}
    p = root / "packs" / "core" / "source_taxonomies.json"
    if not p.exists():
        return {}
    try:
        return json.loads(p.read_text())
    except (OSError, json.JSONDecodeError):
        return {}


def _invert_default_attributions(registry: dict) -> dict[str, list[str]]:
    """Build a {source_taxonomy_prefix: [pattern_id, ...]} index.

    For "what existing catalog covers" lookup. Buckets the
    ``default_attribution_for_uofa_pattern`` table by everything-but-leaf
    so a gap_probe spec under ``gohar/evidence_validity/data-drift`` finds
    UofA patterns that share the ``gohar/evidence_validity/...`` prefix.
    """
    table = registry.get("default_attribution_for_uofa_pattern", {})
    by_prefix: dict[str, list[str]] = {}
    for pat, attribution in table.items():
        if pat == "_comment":
            continue
        if not isinstance(attribution, str) or "/" not in attribution:
            continue
        # Use first two segments as the prefix bucket
        parts = attribution.split("/")
        prefix = "/".join(parts[:2])
        by_prefix.setdefault(prefix, []).append(pat)
    for k in by_prefix:
        by_prefix[k].sort()
    return by_prefix


def _resolve_neighborhood(
    source_taxonomy: str | None, by_prefix: dict[str, list[str]]
) -> list[str]:
    """Return UofA patterns sharing the spec's source_taxonomy prefix."""
    if not source_taxonomy:
        return []
    prefix = "/".join(source_taxonomy.split("/")[:2])
    return by_prefix.get(prefix, [])


def _resolve_taxonomy_citation(
    source_taxonomy: str | None, registry: dict
) -> str:
    """Return the registry's ``citation`` for the taxonomy or a fallback."""
    if not source_taxonomy:
        return "(no source_taxonomy declared)"
    family = source_taxonomy.split("/")[0]
    tax = registry.get("taxonomies", {}).get(family, {})
    return tax.get("citation", f"(no citation registered for {family})")


def _read_spec_text(spec_path: Path) -> str:
    """Read the spec YAML as text for embedding in the packet."""
    try:
        return spec_path.read_text()
    except OSError:
        return f"(could not read {spec_path})"


def _read_representative_package(
    spec_id: str, batch_dir: Path | None
) -> tuple[Path | None, str]:
    """Find a representative variant of *spec_id* and return (path, contents).

    Searches for ``<spec_id>-v01.jsonld`` (or any ``-v\\d+.jsonld``) under the
    batch directory. Returns ``(None, "")`` if nothing found.
    """
    if batch_dir is None or not batch_dir.exists():
        return None, ""
    matches = sorted(batch_dir.rglob(f"{spec_id}-v*.jsonld"))
    if not matches:
        return None, ""
    p = matches[0]
    try:
        return p, p.read_text()
    except OSError:
        return p, ""


def _is_section_6_7_candidate(case: _ReviewableCase) -> bool:
    """True if the row was annotated as a §6.7 candidate.

    Looks at the (optional) ``section_6_7_candidate`` field. Empty/missing
    means False.
    """
    raw = getattr(case, "section_6_7_candidate", None) or ""
    return bool(raw and str(raw).strip().lower() not in ("", "false", "none"))


def _read_outcomes(
    outcomes_path: Path, include_classes: set[str]
) -> list[_ReviewableCase]:
    """Return _ReviewableCase rows filtered to include_classes."""
    cases: list[_ReviewableCase] = []
    if not outcomes_path.exists():
        return cases
    with open(outcomes_path) as f:
        reader = csv.DictReader(f)
        for row in reader:
            if row.get("outcome_class") not in include_classes:
                continue
            cases.append(_ReviewableCase(
                spec_id=row.get("spec_id", ""),
                target_weakener=row.get("target_weakener") or None,
                source_taxonomy=row.get("source_taxonomy") or None,
                coverage_intent=row.get("coverage_intent", ""),
                outcome_class=row.get("outcome_class", ""),
                subtlety=row.get("subtlety", ""),
                rules_fired=row.get("rules_fired", ""),
                is_section_6_7_candidate=bool(row.get("section_6_7_candidate", "")),
            ))
    return cases


def _dedup_by_spec_id(
    cases: list[_ReviewableCase],
) -> list[_ReviewableCase]:
    """Keep the first occurrence per spec_id (stable over outcomes.csv order)."""
    seen: set[str] = set()
    out: list[_ReviewableCase] = []
    for c in cases:
        if c.spec_id in seen:
            continue
        seen.add(c.spec_id)
        out.append(c)
    return out


def _sort_for_index(cases: list[_ReviewableCase]) -> list[_ReviewableCase]:
    """§6.7 candidates first, then by source_taxonomy alpha (None last)."""
    return sorted(
        cases,
        key=lambda c: (
            0 if c.is_section_6_7_candidate else 1,
            c.source_taxonomy or "~",  # ~ sorts after letters
            c.spec_id,
        ),
    )


def _format_packet(
    case: _ReviewableCase,
    spec_path: Path | None,
    package_path: Path | None,
    package_text: str,
    taxonomy_citation: str,
    neighborhood: list[str],
) -> str:
    """Build the per-spec Markdown packet body."""
    lines: list[str] = []
    lines.append(f"# {case.spec_id} — Phase 3 review packet")
    lines.append("")
    lines.append(f"**Outcome class:** `{case.outcome_class}`")
    lines.append(f"**Coverage intent:** `{case.coverage_intent}`")
    lines.append(f"**Subtlety:** `{case.subtlety}`")
    lines.append("")

    lines.append("## Source taxonomy attribution")
    lines.append(f"- **Identifier:** `{case.source_taxonomy or '(not declared)'}`")
    lines.append(f"- **Citation:** {taxonomy_citation}")
    lines.append("")

    lines.append("## Spec description")
    if spec_path is not None:
        lines.append(f"Source spec: `{spec_path}`")
        lines.append("")
        lines.append("```yaml")
        lines.append(_read_spec_text(spec_path))
        lines.append("```")
    else:
        lines.append("*(spec file path not available in outcomes.csv)*")
    lines.append("")

    lines.append("## Generated package")
    lines.append(f"- **Representative variant:** `{package_path or '(not found)'}`")
    lines.append(f"- **Rules fired:** `{case.rules_fired or '(none)'}`")
    lines.append(f"- **Expected target rule:** `{case.target_weakener or '(none — gap_probe)'}`")
    lines.append("")

    lines.append("## What the existing catalog covers in this neighborhood")
    if neighborhood:
        lines.append(
            "Patterns currently attributed to the same source_taxonomy prefix:"
        )
        for pat in neighborhood:
            lines.append(f"- `{pat}`")
    else:
        lines.append(
            "*(No UofA patterns currently attributed to this source_taxonomy "
            "prefix — this is a clean coverage gap.)*"
        )
    lines.append("")

    lines.append("## Reviewer questions")
    lines.append("")
    lines.append(
        "1. **Is the gap genuine?** "
        "(yes / no with rule attribution / partial)"
    )
    lines.append(
        "2. **If genuine, would a new Jena rule be warranted?** "
        "(yes / no / defer)"
    )
    lines.append(
        "3. **Severity classification if new rule warranted:** "
        "(Critical / High / Medium / Low)"
    )
    lines.append("4. **Free-form notes:**")
    lines.append("")

    lines.append("## Representative package (JSON-LD)")
    if package_text:
        lines.append("```json")
        lines.append(package_text)
        lines.append("```")
    else:
        lines.append(
            "*(Package file not located. Check `<batch_dir>/<intent>/<spec_id>/`.)*"
        )
    lines.append("")
    return "\n".join(lines)


def _format_index(cases: list[_ReviewableCase]) -> str:
    """Build INDEX.md per §10.6."""
    lines = [
        "# Phase 3 review packet index",
        "",
        f"Total packets: **{len(cases)}**",
        "",
        "Sorted by §6.7 candidate priority (first), then source_taxonomy.",
        "",
        "| spec_id | source_taxonomy | outcome | §6.7 | packet |",
        "|---|---|---|---|---|",
    ]
    for c in cases:
        candidate_mark = "★" if c.is_section_6_7_candidate else " "
        lines.append(
            f"| `{c.spec_id}` | `{c.source_taxonomy or '—'}` | "
            f"`{c.outcome_class}` | {candidate_mark} | "
            f"[`{c.spec_id}_review.md`](./{c.spec_id}_review.md) |"
        )
    lines.append("")
    return "\n".join(lines)


def run_prep_review(args) -> int:
    """Entry point for ``uofa adversarial prep-review``."""
    outcomes_path: Path = args.outcomes
    output_dir: Path = args.output
    include_classes = _normalize_include(getattr(args, "include", None))
    max_cases = int(getattr(args, "max_cases", 50) or 50)

    if not outcomes_path.exists():
        error(f"outcomes.csv not found: {outcomes_path}")
        return 2

    output_dir.mkdir(parents=True, exist_ok=True)

    info(
        f"reading outcomes from {outcomes_path}; "
        f"include={sorted(include_classes)}; max_cases={max_cases}"
    )
    raw_cases = _read_outcomes(outcomes_path, include_classes)
    if not raw_cases:
        warn("no rows matched --include filter; nothing to write")
        return 1

    deduped = _dedup_by_spec_id(raw_cases)
    sorted_cases = _sort_for_index(deduped)
    capped = sorted_cases[:max_cases]
    info(f"  {len(raw_cases)} matching rows, {len(deduped)} unique, {len(capped)} after cap")

    registry = _load_source_taxonomies()
    by_prefix = _invert_default_attributions(registry)

    # The batch directory is the parent of outcomes.csv (analyze writes
    # outcomes.csv into <batch_dir>/coverage/ by convention; the runner's
    # per-spec output dirs live under <batch_dir>). We search outwards.
    batch_dir = outcomes_path.parent.parent if outcomes_path.parent else None

    for case in capped:
        # Best-effort spec_path resolution: the runner wrote per-spec
        # manifests under <batch_dir>/<intent>/<spec_id>/manifest.json
        # and the spec was loaded from a YAML in specs/<intent>/.
        spec_path = None
        try:
            root = paths.find_repo_root()
        except FileNotFoundError:
            root = None
        if root:
            # Try multiple intent directories
            for intent_dir in ("confirm_existing", "gap_probe",
                               "negative_controls", "interaction"):
                # spec_id includes the prefix adv-2026-... — direct lookup
                # by stem won't work uniformly. Try the spec_id stem and
                # a few common name patterns.
                cand = root / "specs" / intent_dir
                if cand.exists():
                    matches = list(cand.glob(f"*{case.spec_id}*.yaml"))
                    if matches:
                        spec_path = matches[0]
                        break

        package_path, package_text = _read_representative_package(
            case.spec_id, batch_dir
        )
        taxonomy_citation = _resolve_taxonomy_citation(
            case.source_taxonomy, registry
        )
        neighborhood = _resolve_neighborhood(case.source_taxonomy, by_prefix)

        packet = _format_packet(
            case=case,
            spec_path=spec_path,
            package_path=package_path,
            package_text=package_text,
            taxonomy_citation=taxonomy_citation,
            neighborhood=neighborhood,
        )
        out_md = output_dir / f"{case.spec_id}_review.md"
        out_md.write_text(packet)

    index_md = output_dir / "INDEX.md"
    index_md.write_text(_format_index(capped))

    result_line("review_packets", True, str(output_dir))
    result_line("review_index", True, str(index_md))
    info(f"wrote {len(capped)} packet(s)")
    return 0
